import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/about'
import ContactUs from '../components/contactus'
import Footer from '../components/footer'
import Masthead from '../components/masthead'
import Skills from '../components/skills'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DabAZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>

      <Masthead />
      <About />
      <Skills />
      <ContactUs />
      <Footer />

    </div>
  )
}

export default Home
